//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMDiscordRPC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMDiscordRPC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;playButtons&quot;: [&quot;Speel&quot;,&quot;\u12A0\u132B\u12CD\u1275&quot;,&quot;\u200F\u200F\u062A\u0634\u063A\u064A\u0644&quot;,&quot;\u09AA\u09CD\u09B2\u09C7 \u0995\u09F0\u0995&quot;,&quot;\u0130fa et&quot;,&quot;\u0418\u0437\u043F\u044A\u043B\u043D\u0438&quot;,&quot;\u09AA\u09CD\u09B2\u09C7 \u0995\u09B0\u09C1\u09A8&quot;,&quot;Reproduciraj&quot;,&quot;Reprodueix&quot;,&quot;Reprodueix&quot;,&quot;P\u0159ehr\u00E1t&quot;,&quot;Chwarae&quot;,&quot;Afspil&quot;,&quot;Wiedergeben&quot;,&quot;\u0391\u03BD\u03B1\u03C0\u03B1\u03C1\u03B1\u03B3\u03C9\u03B3\u03AE&quot;,&quot;Play&quot;,&quot;Play&quot;,&quot;Reproducir&quot;,&quot;Reproducir&quot;,&quot;Esita&quot;,&quot;Erreproduzitu&quot;,&quot;\u200F\u200F\u067E\u062E\u [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ButtonValues {
            get {
                return ResourceManager.GetString("ButtonValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo_Black {
            get {
                object obj = ResourceManager.GetObject("Logo_Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Logo_Black_32 {
            get {
                object obj = ResourceManager.GetObject("Logo_Black_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Logo_Black1 {
            get {
                object obj = ResourceManager.GetObject("Logo_Black1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
