name: Build .NET Framework

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
    - name: Download DiscordRPC Package
      run: mkdir "${{ runner.temp }}/local-packages" && powershell Invoke-WebRequest "https://github.com/Lachee/discord-rpc-csharp/releases/download/v1.3.0/DiscordRichPresence.1.3.0.28.nupkg" -OutFile "${{ runner.temp }}/local-packages/DiscordRichPresence.1.3.0.28.nupkg" && powershell Install-PackageProvider -Name NuGet -Force
    - name: Create Trusted Repo 
      run: powershell Register-PackageSource -Name LocalPackages -Location "${{ runner.temp }}/local-packages/" -ProviderName NuGet -Trusted
    - name: Install DiscordRPC Package
      run: powershell Install-Package -Name DiscordRichPresence -SkipDependencies -Source LocalPackages -Force
    - name: Restore NuGet Packages
      run: nuget restore AMDiscordRPC.sln
    - name: Build
      run: msbuild AMDiscordRPC.sln -property:Configuration=Release -property:platform="x64"
    - name: Zip
      run: powershell Compress-Archive -Path ./AMDiscordRPC/bin/x64/Release -DestinationPath Release.zip
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.run_id }}
        name: Release BuildID-${{ github.run_id }}
        files: |
          Release.zip